import type { AttachmentPage, AttachmentProcessorContext } from "./mv-background-uploads";
import { isPdfFile, renderPdfPageToJpegFile } from "@/components/workspace/workspace-sections/machine-valuation/mv-pdf-page-images";
import { prepareValuationAccountingUploadFile } from "@/components/workspace/workspace-sections/machine-valuation/mv-project-gridfs-upload";

export async function processAttachment({ job, item, file, checkpoint, readFile, request, active, invalidate }: AttachmentProcessorContext) {
  const attachment = job.attachment!;
  const base = `/api/mv/projects/${encodeURIComponent(job.projectId)}/attachment-jobs/${job.id}`;
  const kind = isPdfFile(file) ? "pdf" : /\.(xlsx?|xlsm|csv)$/i.test(file.name) ? "excel" : "image";
  const source = item.source ??= {
    id: item.id, kind, name: item.path || file.name, originalName: file.name,
    mimeType: file.type, sizeBytes: file.size, createdAt: new Date(job.createdAt).toISOString(),
    ...(attachment.approachId ? { approachId: attachment.approachId, excelRowsPerImage: attachment.rowsPerImage ?? 50 } : {}),
  };
  item.pages ??= [];
  const checkActive = () => { if (!active()) throw new Error("تم إيقاف المهمة مؤقتًا بسبب تغيير الحساب."); };
  // Preserve source documents for the existing PDF/Excel editors when the proxy permits it.
  if (!source.fileId && !source.originalSkipped) {
    if (file.size > 25 * 1024 * 1024) source.originalSkipped = true;
    else {
      const form = new FormData(); form.append("file", file, file.name);
      try {
        const result = await request(`${base}/original/${item.id}`, { method: "POST", body: form });
        if (!result?.fileId) throw new Error("لم يُؤكد حفظ الملف الأصلي.");
        source.fileId = result.fileId;
      } catch (error) {
        if ((error as { status?: number }).status !== 413) throw error;
        source.originalSkipped = true;
      }
    }
    await checkpoint();
  }
  let plannedTotal: number | undefined;
  const plan = async (total: number) => {
    checkActive();
    if (plannedTotal === total) return;
    await request(`${base}/plan`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourceId: item.id, total }) });
    plannedTotal = total;
  };
  const savePage = async (page: AttachmentPage) => {
    if (page.saved) return;
    checkActive();
    job.phase = "saving";
    await checkpoint();
    const blob = await readFile(page.blobKey);
    if (!blob) throw new Error("الصورة المحولة غير متاحة على الجهاز.");
    const form = new FormData();
    form.append("file", blob, blob.name);
    form.append("metadata", JSON.stringify({ source, image: { ...page.image, autoPageIndex: page.index } }));
    const receipt = await request(`${base}/pages`, { method: "POST", body: form });
    if (!receipt?.fileId || receipt.imageId !== `${item.id}-page-${page.index}`) throw new Error("لم يُؤكد حفظ الصورة في التقرير.");
    page.saved = true;
    await checkpoint();
    invalidate();
  };
  const capture = async (imageFile: File, index: number, total: number, image: Record<string, unknown> = {}) => {
    checkActive();
    let page = item.pages!.find(row => row.index === index);
    if (!page) {
      imageFile = await prepareValuationAccountingUploadFile(imageFile, 3.5 * 1024 * 1024);
      if (!imageFile.type) {
        const extension = imageFile.name.split(".").pop()?.toLowerCase();
        const mime = extension === "jpg" || extension === "jpeg" ? "image/jpeg" : `image/${extension}`;
        imageFile = new File([imageFile], imageFile.name, { type: mime });
      }
      page = { index, total, blobKey: `${item.id}-page-${index}`, image: { name: `${source.name} — ${index} / ${total}`, ...image } };
      item.pages!.push(page);
      // Generated bytes and their metadata become durable before any network upload.
      try { await checkpoint({ value: page, file: imageFile }); }
      catch (error) {
        item.pages = item.pages!.filter(row => row !== page);
        throw error;
      }
    }
    await savePage(page);
  };
  // Resume saved renders first; do not render or upload acknowledged pages again.
  if (item.pages.length) await plan(item.pages[0].total);
  for (const page of item.pages) await savePage(page);
  if (item.converted) return;
  job.phase = "converting";
  await checkpoint();
  if (kind === "pdf") {
    const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");
    pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/legacy/build/pdf.worker.min.mjs", import.meta.url).toString();
    const pdf = await pdfjs.getDocument({ data: new Uint8Array(await file.arrayBuffer()) }).promise;
    try {
      await plan(pdf.numPages);
      for (let index = 1; index <= pdf.numPages; index++) {
        checkActive();
        if (item.pages.some(page => page.index === index)) continue;
        job.phase = "converting"; await checkpoint();
        const rendered = await renderPdfPageToJpegFile(pdf, index, pdf.numPages, file.name.replace(/\.[^.]+$/, ""));
        await capture(rendered.file, index, pdf.numPages);
      }
    } finally { await pdf.destroy(); }
  } else if (kind === "excel") {
    const { buildExcelImagesDirectlyFromOriginalFile } = await import("@/components/workspace/workspace-sections/machine-valuation/mv-valuation-accounting-workspace");
    await buildExcelImagesDirectlyFromOriginalFile({ projectId: job.projectId, file,
      source: source as any, rowsPerImage: attachment.rowsPerImage ?? 50,
      onProgress: async (_done, total) => { if (total) await plan(total); },
      control: { concurrency: 1, skipPage: index => item.pages!.some(page => page.index === index),
        capture: async (imageFile, image) => { await capture(imageFile, image.autoPageIndex!, image.autoPageCount!, image as unknown as Record<string, unknown>); },
        shouldStop: () => !active(),
      },
    });
    checkActive();
  } else {
    await plan(1);
    await capture(file, 1, 1);
  }
  if (!item.pages.length || item.pages.length !== item.pages[0].total) throw new Error("لم يكتمل تحويل جميع صفحات المرفق.");
  item.converted = true;
  await checkpoint();
}
