export type MvClientDocumentFileKind = "pdf" | "image";

export interface MvClientDocumentSource {
  id: string;
  kind: MvClientDocumentFileKind;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  createdAt: string;
  fileId?: string;
  dataUrl?: string;
}

export interface MvClientDocumentImage {
  id: string;
  sourceId: string;
  sourceKind: MvClientDocumentFileKind;
  sourceFileName: string;
  name: string;
  fileId?: string;
  dataUrl?: string;
  createdAt: string;
  includeInReport?: boolean;
  autoGenerated?: boolean;
  autoPageIndex?: number;
  autoPageCount?: number;
}

export interface MvClientDocumentsStore {
  version: 1;
  includeInReport: boolean;
  sources: MvClientDocumentSource[];
  images: MvClientDocumentImage[];
  updatedAt?: string;
}

const STORAGE_PREFIX = "sv:mv-client-documents:";

export function clientDocumentsStorageKey(projectId: string) {
  return `${STORAGE_PREFIX}${projectId}`;
}

export function emptyClientDocumentsStore(): MvClientDocumentsStore {
  return {
    version: 1,
    includeInReport: true,
    sources: [],
    images: [],
  };
}

export function resolveClientDocumentImageSrc(
  projectId: string,
  image: { dataUrl?: string; fileId?: string },
): string {
  if (image.fileId) {
    return `/api/mv/projects/${encodeURIComponent(projectId)}/files/${encodeURIComponent(image.fileId)}/download`;
  }
  if (image.dataUrl) return image.dataUrl;
  return "";
}

function stripRedundantDataUrls(store: MvClientDocumentsStore): MvClientDocumentsStore {
  return {
    ...store,
    sources: store.sources.map((s) => {
      if (!s.fileId || !s.dataUrl) return s;
      const { dataUrl: _d, ...rest } = s;
      return rest;
    }),
    images: store.images.map((im) => {
      if (!im.fileId || !im.dataUrl) return im;
      const { dataUrl: _d, ...rest } = im;
      return rest;
    }),
  };
}

function isFileKind(value: unknown): value is MvClientDocumentFileKind {
  return value === "pdf" || value === "image";
}

function normalizeSource(value: unknown): MvClientDocumentSource | null {
  if (!value || typeof value !== "object") return null;
  const item = value as Partial<MvClientDocumentSource>;
  if (typeof item.id !== "string" || !isFileKind(item.kind) || typeof item.name !== "string") {
    return null;
  }
  return {
    id: item.id,
    kind: item.kind,
    name: item.name,
    originalName: typeof item.originalName === "string" ? item.originalName : item.name,
    mimeType: typeof item.mimeType === "string" ? item.mimeType : "",
    sizeBytes: typeof item.sizeBytes === "number" ? item.sizeBytes : 0,
    createdAt: typeof item.createdAt === "string" ? item.createdAt : new Date().toISOString(),
    fileId: typeof item.fileId === "string" && item.fileId.trim() ? item.fileId : undefined,
    dataUrl: typeof item.dataUrl === "string" ? item.dataUrl : undefined,
  };
}

function normalizeImage(value: unknown): MvClientDocumentImage | null {
  if (!value || typeof value !== "object") return null;
  const item = value as Partial<MvClientDocumentImage>;
  if (
    typeof item.id !== "string" ||
    typeof item.sourceId !== "string" ||
    !isFileKind(item.sourceKind) ||
    typeof item.name !== "string"
  ) {
    return null;
  }
  const fileId = typeof item.fileId === "string" && item.fileId.trim() ? item.fileId : undefined;
  const dataUrl = typeof item.dataUrl === "string" && item.dataUrl.trim() ? item.dataUrl : undefined;
  if (!fileId && !dataUrl) return null;
  return {
    id: item.id,
    sourceId: item.sourceId,
    sourceKind: item.sourceKind,
    sourceFileName: typeof item.sourceFileName === "string" ? item.sourceFileName : "مستند عميل",
    name: item.name,
    fileId,
    dataUrl,
    createdAt: typeof item.createdAt === "string" ? item.createdAt : new Date().toISOString(),
    includeInReport: item.includeInReport !== false,
    autoGenerated: item.autoGenerated === true,
    autoPageIndex:
      typeof item.autoPageIndex === "number" ? Math.max(1, Math.round(item.autoPageIndex)) : undefined,
    autoPageCount:
      typeof item.autoPageCount === "number" ? Math.max(1, Math.round(item.autoPageCount)) : undefined,
  };
}

export function parseClientDocumentsStoreFromApi(raw: unknown): MvClientDocumentsStore | null {
  if (!raw || typeof raw !== "object") return null;
  const parsed = raw as Partial<MvClientDocumentsStore>;
  if (parsed.version !== 1) return null;
  return stripRedundantDataUrls({
    version: 1,
    includeInReport: parsed.includeInReport !== false,
    sources: Array.isArray(parsed.sources)
      ? parsed.sources.map(normalizeSource).filter((item): item is MvClientDocumentSource => Boolean(item))
      : [],
    images: Array.isArray(parsed.images)
      ? parsed.images.map(normalizeImage).filter((item): item is MvClientDocumentImage => Boolean(item))
      : [],
    updatedAt: typeof parsed.updatedAt === "string" ? parsed.updatedAt : undefined,
  });
}

export function mergeClientDocumentsStores(
  serverRaw: unknown,
  local: MvClientDocumentsStore,
): MvClientDocumentsStore {
  const fromServer = parseClientDocumentsStoreFromApi(serverRaw);
  if (!fromServer) return stripRedundantDataUrls(local);
  const sTime = fromServer.updatedAt ? Date.parse(fromServer.updatedAt) : 0;
  const lTime = local.updatedAt ? Date.parse(local.updatedAt) : 0;
  if (sTime > lTime) return fromServer;
  if (lTime > sTime) return stripRedundantDataUrls(local);
  const sScore = fromServer.sources.length + fromServer.images.length;
  const lScore = local.sources.length + local.images.length;
  return stripRedundantDataUrls(sScore >= lScore ? fromServer : local);
}

export function clientDocumentsStoreForApi(store: MvClientDocumentsStore): MvClientDocumentsStore {
  return stripRedundantDataUrls(store);
}

export function readClientDocumentsStore(projectId: string): MvClientDocumentsStore {
  if (typeof window === "undefined") return emptyClientDocumentsStore();
  try {
    const raw =
      window.localStorage.getItem(clientDocumentsStorageKey(projectId)) ??
      window.sessionStorage.getItem(clientDocumentsStorageKey(projectId));
    if (!raw) return emptyClientDocumentsStore();
    return parseClientDocumentsStoreFromApi(JSON.parse(raw)) ?? emptyClientDocumentsStore();
  } catch {
    return emptyClientDocumentsStore();
  }
}

export function writeClientDocumentsStore(projectId: string, store: MvClientDocumentsStore): boolean {
  if (typeof window === "undefined") return true;
  const next: MvClientDocumentsStore = stripRedundantDataUrls({
    ...store,
    version: 1,
    updatedAt: new Date().toISOString(),
  });
  const raw = JSON.stringify(next);
  try {
    window.localStorage.setItem(clientDocumentsStorageKey(projectId), raw);
    window.sessionStorage.setItem(clientDocumentsStorageKey(projectId), raw);
    return true;
  } catch {
    try {
      window.sessionStorage.setItem(clientDocumentsStorageKey(projectId), raw);
      return true;
    } catch {
      return false;
    }
  }
}

export function createClientDocumentId(prefix: string) {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

/** صور مرفقة بالتقرير فقط، مرتّبة كما في المخزن */
export function clientDocumentImagesForReport(store: MvClientDocumentsStore | null | undefined): MvClientDocumentImage[] {
  if (!store || store.includeInReport === false) return [];
  return store.images.filter((im) => im.includeInReport !== false);
}
