import type { ActiveImportSheetRef, AssetImportResult } from "./asset-import-panel";

export const MV_VALUATION_ACCOUNTING_APPROACHES = [
  { id: "cost", label: "أسلوب التكلفة", shortLabel: "التكلفة" },
  { id: "market", label: "أسلوب السوق", shortLabel: "السوق" },
  { id: "comparisons", label: "المقارنات", shortLabel: "المقارنات" },
] as const;

export type MvValuationAccountingApproachId =
  (typeof MV_VALUATION_ACCOUNTING_APPROACHES)[number]["id"];

export type MvValuationAccountingFileKind = "excel" | "pdf" | "image";

export const MV_VALUATION_ACCOUNTING_FILE_KIND_LABEL: Record<
  MvValuationAccountingFileKind,
  string
> = {
  excel: "Excel",
  pdf: "PDF",
  image: "صورة",
};

export interface MvValuationAccountingSourceFile {
  id: string;
  approachId: MvValuationAccountingApproachId;
  kind: MvValuationAccountingFileKind;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  createdAt: string;
  /**
   * Server-stored file id (DigitalOcean Spaces via backend).
   * Preferred over `dataUrl` to avoid huge localStorage payloads and blank renders.
   */
  fileId?: string;
  /** Legacy/local fallback for older sessions (may be removed later). */
  dataUrl?: string;
  /** مصدر بيانات Excel داخل إجراءات التقييم. القيم الجديدة لا تستخدم assets إطلاقاً. */
  excelDataSource?: "mv-sheets" | "assets-import";
  /** عدد صفوف البيانات في كل صورة تلقائية مولّدة من Excel. */
  excelRowsPerImage?: number;
  /** الأعمدة المختارة للظهور في صور Excel، مفاتيحها حسب اسم الشيت. غيابها يعني كل الأعمدة ظاهرة. */
  excelVisibleColumnsBySheet?: Record<string, string[]>;
  /** مقاسات يدوية لأعمدة Excel في المعاينة والصور، مفاتيحها حسب اسم الشيت ثم اسم العمود. */
  excelColumnSizesBySheet?: Record<string, Record<string, { widthPx?: number; minHeightPx?: number }>>;
  importResult?: AssetImportResult;
  activeSheet?: ActiveImportSheetRef | null;
}

export interface MvValuationAccountingImage {
  id: string;
  approachId: MvValuationAccountingApproachId;
  sourceId: string;
  sourceKind: MvValuationAccountingFileKind;
  sourceFileName: string;
  name: string;
  /**
   * Server-stored cropped image file id (DigitalOcean Spaces via backend).
   * Preferred over `dataUrl`.
   */
  fileId?: string;
  /** Legacy/local fallback for older sessions (may be removed later). */
  dataUrl?: string;
  createdAt: string;
  displayWidthPercent: number;
  displayMaxHeightPx: number;
  qualityScale: number;
  includeInReport?: boolean;
  autoGenerated?: boolean;
  autoPageIndex?: number;
  autoPageCount?: number;
  autoRowsPerImage?: number;
  crop?: {
    pageNumber?: number;
    sheetName?: string;
    x: number;
    y: number;
    width: number;
    height: number;
  };
}

export interface MvValuationAccountingStore {
  version: 1;
  includeInReport: boolean;
  sources: MvValuationAccountingSourceFile[];
  images: MvValuationAccountingImage[];
  updatedAt?: string;
}

const STORAGE_PREFIX = "sv:mv-valuation-accounting:";

export function valuationAccountingStorageKey(projectId: string) {
  return `${STORAGE_PREFIX}${projectId}`;
}

export function emptyValuationAccountingStore(): MvValuationAccountingStore {
  return {
    version: 1,
    includeInReport: true,
    sources: [],
    images: [],
  };
}

export function approachLabel(id: MvValuationAccountingApproachId) {
  return MV_VALUATION_ACCOUNTING_APPROACHES.find((item) => item.id === id)?.label ?? id;
}

function isApproachId(value: unknown): value is MvValuationAccountingApproachId {
  return MV_VALUATION_ACCOUNTING_APPROACHES.some((item) => item.id === value);
}

function isFileKind(value: unknown): value is MvValuationAccountingFileKind {
  return value === "excel" || value === "pdf" || value === "image";
}

function normalizeSource(value: unknown): MvValuationAccountingSourceFile | null {
  if (!value || typeof value !== "object") return null;
  const item = value as Partial<MvValuationAccountingSourceFile>;
  if (
    typeof item.id !== "string" ||
    !isApproachId(item.approachId) ||
    !isFileKind(item.kind) ||
    typeof item.name !== "string"
  ) {
    return null;
  }
  return {
    id: item.id,
    approachId: item.approachId,
    kind: item.kind,
    name: item.name,
    originalName: typeof item.originalName === "string" ? item.originalName : item.name,
    mimeType: typeof item.mimeType === "string" ? item.mimeType : "",
    sizeBytes: typeof item.sizeBytes === "number" ? item.sizeBytes : 0,
    createdAt: typeof item.createdAt === "string" ? item.createdAt : new Date().toISOString(),
    fileId: typeof item.fileId === "string" && item.fileId.trim() ? item.fileId : undefined,
    dataUrl: typeof item.dataUrl === "string" ? item.dataUrl : undefined,
    excelDataSource:
      item.excelDataSource === "mv-sheets" || item.excelDataSource === "assets-import"
        ? item.excelDataSource
        : undefined,
    excelRowsPerImage:
      typeof item.excelRowsPerImage === "number"
        ? Math.min(20, Math.max(5, Math.round(item.excelRowsPerImage)))
        : undefined,
    excelVisibleColumnsBySheet:
      item.excelVisibleColumnsBySheet && typeof item.excelVisibleColumnsBySheet === "object"
        ? item.excelVisibleColumnsBySheet
        : undefined,
    excelColumnSizesBySheet:
      item.excelColumnSizesBySheet && typeof item.excelColumnSizesBySheet === "object"
        ? item.excelColumnSizesBySheet
        : undefined,
    importResult: item.importResult,
    activeSheet: item.activeSheet ?? null,
  };
}

function normalizeImage(value: unknown): MvValuationAccountingImage | null {
  if (!value || typeof value !== "object") return null;
  const item = value as Partial<MvValuationAccountingImage>;
  if (
    typeof item.id !== "string" ||
    !isApproachId(item.approachId) ||
    typeof item.sourceId !== "string" ||
    !isFileKind(item.sourceKind) ||
    typeof item.name !== "string"
  ) {
    return null;
  }
  const fileId = typeof item.fileId === "string" && item.fileId.trim() ? item.fileId : undefined;
  const dataUrl = typeof item.dataUrl === "string" && item.dataUrl.trim() ? item.dataUrl : undefined;
  if (!fileId && !dataUrl) return null;
  return {
    id: item.id,
    approachId: item.approachId,
    sourceId: item.sourceId,
    sourceKind: item.sourceKind,
    sourceFileName:
      typeof item.sourceFileName === "string" ? item.sourceFileName : "ملف حسابات",
    name: item.name,
    fileId,
    dataUrl,
    createdAt: typeof item.createdAt === "string" ? item.createdAt : new Date().toISOString(),
    displayWidthPercent:
      typeof item.displayWidthPercent === "number"
        ? Math.min(100, Math.max(24, item.displayWidthPercent))
        : 84,
    displayMaxHeightPx:
      typeof item.displayMaxHeightPx === "number"
        ? Math.min(1400, Math.max(180, item.displayMaxHeightPx))
        : 620,
    qualityScale:
      typeof item.qualityScale === "number"
        ? Math.min(4, Math.max(1, item.qualityScale))
        : 2.5,
    includeInReport: item.includeInReport !== false,
    autoGenerated: item.autoGenerated === true,
    autoPageIndex:
      typeof item.autoPageIndex === "number" ? Math.max(1, Math.round(item.autoPageIndex)) : undefined,
    autoPageCount:
      typeof item.autoPageCount === "number" ? Math.max(1, Math.round(item.autoPageCount)) : undefined,
    autoRowsPerImage:
      typeof item.autoRowsPerImage === "number"
        ? Math.min(20, Math.max(5, Math.round(item.autoRowsPerImage)))
        : undefined,
    crop: item.crop,
  };
}

/** تطبيع كائن مستلم من API أو تخزين — بدون قراءة window */
export function parseValuationAccountingStoreFromApi(raw: unknown): MvValuationAccountingStore | null {
  if (!raw || typeof raw !== "object") return null;
  const parsed = raw as Partial<MvValuationAccountingStore>;
  if (parsed.version !== 1) return null;
  return {
    version: 1,
    includeInReport: parsed.includeInReport !== false,
    sources: Array.isArray(parsed.sources)
      ? parsed.sources.map(normalizeSource).filter((item): item is MvValuationAccountingSourceFile => Boolean(item))
      : [],
    images: Array.isArray(parsed.images)
      ? parsed.images.map(normalizeImage).filter((item): item is MvValuationAccountingImage => Boolean(item))
      : [],
    updatedAt: typeof parsed.updatedAt === "string" ? parsed.updatedAt : undefined,
  };
}

/** دمج: الأحدث حسب ‎updatedAt‎؛ عند التعادل يُفضَّل الأكثر مصادر/صوراً */
export function mergeValuationAccountingStores(
  serverRaw: unknown,
  local: MvValuationAccountingStore,
): MvValuationAccountingStore {
  const fromServer = parseValuationAccountingStoreFromApi(serverRaw);
  if (!fromServer) return local;
  const sTime = fromServer.updatedAt ? Date.parse(fromServer.updatedAt) : 0;
  const lTime = local.updatedAt ? Date.parse(local.updatedAt) : 0;
  if (sTime > lTime) return fromServer;
  if (lTime > sTime) return local;
  const sScore = fromServer.sources.length + fromServer.images.length;
  const lScore = local.sources.length + local.images.length;
  return sScore >= lScore ? fromServer : local;
}

/** إزالة ‎dataUrl‎ قبل إرسالها للخادم (تخفيف حجم المستند) */
export function valuationAccountingStoreForApi(store: MvValuationAccountingStore): MvValuationAccountingStore {
  return {
    ...store,
    sources: store.sources.map((s) => {
      if (s.fileId) {
        const { dataUrl: _d, ...rest } = s;
        return rest;
      }
      return s;
    }),
    images: store.images.map((im) => {
      if (im.fileId) {
        const { dataUrl: _d, ...rest } = im;
        return rest;
      }
      return im;
    }),
  };
}

export function readValuationAccountingStore(projectId: string): MvValuationAccountingStore {
  if (typeof window === "undefined") return emptyValuationAccountingStore();
  try {
    const raw =
      window.localStorage.getItem(valuationAccountingStorageKey(projectId)) ??
      window.sessionStorage.getItem(valuationAccountingStorageKey(projectId));
    if (!raw) return emptyValuationAccountingStore();
    const parsed = JSON.parse(raw) as unknown;
    return parseValuationAccountingStoreFromApi(parsed) ?? emptyValuationAccountingStore();
  } catch {
    return emptyValuationAccountingStore();
  }
}

export function writeValuationAccountingStore(
  projectId: string,
  store: MvValuationAccountingStore,
): boolean {
  if (typeof window === "undefined") return true;
  const next: MvValuationAccountingStore = {
    ...store,
    version: 1,
    updatedAt: new Date().toISOString(),
  };
  const raw = JSON.stringify(next);
  try {
    window.localStorage.setItem(valuationAccountingStorageKey(projectId), raw);
    window.sessionStorage.setItem(valuationAccountingStorageKey(projectId), raw);
    return true;
  } catch {
    try {
      window.sessionStorage.setItem(valuationAccountingStorageKey(projectId), raw);
      return true;
    } catch {
      return false;
    }
  }
}
